### ISSUE TITLE
One-sided test

### ISSUE THREAD

**Issue by sanghyeonp** [gqi/fastASSET#1]
Hi all,

Would it be possible to conduct a one-sided test instead of a two-sided for the fast_asset function?

Thanks,

**Comment by gqi** [comment]
Currently fast_asset only allows two-sided tests. fast_asset is developed to speed up computation when analyzing a large number of traits, in which case we think the one-sided ASSET assumption that the genetic effects on all traits are in the same direction are unlikely to hold. If you are looking at the smaller number of traits, I would suggest using the original ASSET, which should have better power.

**Comment by sanghyeonp** [comment]
I see. I'll look into the original ASSET tool.

Thank you!
